name = "telegram-replies-only-bot"
workers_dev = true
usage_model = "bundled"
compatibility_date = "2022-06-24"

main = "./dist/index.mjs"
minify = true

[dev]
port = 8080

[vars]

[[kv_namespaces]]
binding = "LOGS"
id = "%%LOGS%%"
preview_id = ""

[[kv_namespaces]]
binding = "SETTINGS"
id = "%%SETTINGS%%"
preview_id = ""
