name = "telegram-replies-only-bot"
type = "javascript"
account_id = ""
workers_dev = true
compatibility_date = "2021-12-26"

[[kv_namespaces]]
binding = "LOGS"
id = "%%LOGS%%"

[vars]
HOOK_PATH = "%%HOOK_PATH%%"
TELEGRAM_API_TOKEN = "%%TELEGRAM_API_TOKEN%%"
ALLOWED_CHAT_IDS = ""

[dev]
port = 8080

[build.upload]
format = "modules"
main = "./index.mjs"
