name = "telegram-replies-only-bot"
type = "javascript"
account_id = ""
workers_dev = true
compatibility_date = "2022-06-24"

[[kv_namespaces]]
binding = "LOGS"
id = "%%LOGS%%"

[[kv_namespaces]]
binding = "SETTINGS"
id = "%%SETTINGS%%"

[vars]
HOOK_PATH = "%%HOOK_PATH%%"
TELEGRAM_API_TOKEN = "%%TELEGRAM_API_TOKEN%%"

[dev]
port = 8080

[build.upload]
format = "modules"
main = "./index.mjs"
