name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2

      - name: Create wrangler.toml
        uses: bluwy/substitute-string-action@v1
        with:
          _input-file: 'wrangler.example.toml'
          _output-file: 'wrangler.toml'
          _format-key: '%%key%%'
          LOGS: ${{ secrets.LOGS }}
          HOOK_PATH: ${{ secrets.HOOK_PATH }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          publish: false
          preCommands: |
            npm ci
            npm run-script build
            wrangler publish
