name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create wrangler.toml
        uses: bluwy/substitute-string-action@v1
        with:
          _input-file: 'wrangler.example.toml'
          _output-file: 'wrangler.toml'
          _format-key: '%%key%%'
          LOGS: ${{ secrets.LOGS }}
          SETTINGS: ${{ secrets.SETTINGS }}
          HOOK_PATH: ${{ secrets.HOOK_PATH }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run-script build

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          publish: false
          preCommands: |
            json="$(wrangler publish -- json)"
            echo "::set-output name=value::$json"

      - name: Check status
        uses: srt32/uptime@master
        with:
          url-to-hit: ${{ fromJSON(steps.deploy.outputs.value).urls[0] }}/status
